version: "3.7"

services:
    nginx:
        container_name: "${REINDEX_PROJECT_NAME}_nginx"
        image: nginx:$NGINX_IMAGE_VERSION
        volumes:
            - "./custom/nginx/${NGINX_DEFAULT_CONF_FILENAME}:/etc/nginx/conf.d/${NGINX_DEFAULT_CONF_FILENAME}.template"
            - "./custom/nginx/${NGINX_MAIN_CONF_FILENAME}:/etc/nginx/${NGINX_MAIN_CONF_FILENAME}.template"
        ports:
            - "${NGINX_PORT}:${NGINX_PORT}"
        environment:
            NGINX_PORT: $NGINX_PORT
        command: /bin/bash -c "envsubst < /etc/nginx/conf.d/${NGINX_DEFAULT_CONF_FILENAME}.template > /etc/nginx/conf.d/${NGINX_DEFAULT_CONF_FILENAME} && envsubst < /etc/nginx/${NGINX_MAIN_CONF_FILENAME}.template > /etc/nginx/nginx.conf && exec nginx-debug -g 'daemon off;'"

    elasticsearch:
        container_name: "${REINDEX_PROJECT_NAME}_elasticsearch"
        image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTICSEARCH_IMAGE_VERSION
        environment:
            - "cluster.name=${ELASTICSEARCH_CLUSTER_NAME}"
            - "bootstrap.memory_lock=${ELASTICSEARCH_MEMORY_LOCK}"
            - "ES_JAVA_OPTS=-Xms${ELASTICSEARCH_MIN_HEAP_SIZE} -Xmx${ELASTICSEARCH_MAX_HEAP_SIZE}"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - "${ELASTICSEARCH_PORT}:9200"
            - "${ELASTICSEARCH_DISCOVERY_PORT}:9300"
        volumes:
            - "esdata:/usr/share/elasticsearch/data"

    kibana:
        container_name: "${REINDEX_PROJECT_NAME}_kibana"
        image: docker.elastic.co/kibana/kibana:$KIBANA_IMAGE_VERSION
        ports:
            - "${KIBANA_PORT}:5601"
        environment:
            ELASTICSEARCH_HOSTS: "elasticsearch:9200"

    elastichq:
        container_name: "${REINDEX_PROJECT_NAME}_elastichq"
        image: elastichq/elasticsearch-hq:$ELASTICHQ_IMAGE_VERSION
        ports:
            - "${ELASTICHQ_PORT}:5000"
        environment:
            HQ_DEFAULT_URL: "http://localhost:${ELASTICSEARCH_PORT}"

    wordpress:
        container_name: "${REINDEX_PROJECT_NAME}_wp"
        image: wordpress:$WORDPRESS_IMAGE_VERSION
        depends_on:
            - mysql
        environment:
            WORDPRESS_DB_HOST: $WORDPRESS_DB_HOST
            WORDPRESS_DB_USER: $WORDPRESS_DB_USER
            WORDPRESS_DB_PASSWORD: $WORDPRESS_DB_PASSWORD
            WORDPRESS_DB_NAME: $WORDPRESS_DB_NAME

    mysql:
        container_name: "${REINDEX_PROJECT_NAME}_mysql"
        image: mysql:$MYSQL_IMAGE_VERSION
        volumes:
            - "./data/mysql:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: $WORDPRESS_DB_NAME
            MYSQL_USER: $WORDPRESS_DB_USER
            MYSQL_PASSWORD: $WORDPRESS_DB_PASSWORD


volumes:
    esdata:
